### ISSUE TITLE
Non-minified version lacks CSS

### ISSUE THREAD

**Issue by shaunwinters** [mikewgd/console-log#7]
The non-minified version of console.js lacks the CSS required to render the console properly. Instead, there's a **{{consoleLogStyles}}** tag where it should be, with the comment **// Replaced by a grunt task**

**Comment by mikewgd** [comment]
@shaunwinters I have implemented a build process for the repo. The console.js within the js folder still has the {{consoleLogStyles}} but the dist folder has a console.js and console.min.js file. Both contain the CSS string.
